### ISSUE TITLE
i get this error (standard_in) 1: syntax error

### ISSUE THREAD

**Issue by diederikm** [cptmorgan-rh/quicksync_calc#3]
Doing this on Unraid, added jq and bc via a nerdtool package, i get the following error

> 
=== CPU only test
h264_1080p_cpu - h264 to h264 cpu starting.
=== QSV test
h264_1080p - h264 to h264_qsv starting.
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
=== QSV test
h264_4k - h264 to h264_qsv starting.
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
=== QSV test
hevc_1080p_8bit - hevc 8bit to hevc_qsv starting.
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
=== QSV test
hevc_4k - hevc 10bit to hevc_qsv starting.
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
CPU     TEST            FILE                        BITRATE     TIME      AVG_FPS  AVG_SPEED  AVG_WATTS
Silver  h264_1080p_cpu  ribblehead_1080p_h264       18952 kb/s  185.875s  19.53    .69x       N/A
Silver  h264_1080p      ribblehead_1080p_h264       18952 kb/s                     x
Silver  h264_4k         ribblehead_4k_h264          46881 kb/s                     x
Silver  hevc_8bit       ribblehead_1080p_hevc_8bit  14947 kb/s                     x
Silver  hevc_4k_10bit   ribblehead_4k_hevc_10bit    44617 kb/s                     x
>

**Comment by diederikm** [comment]
i think i resolved it myself for a bit, still get "(standard_in) 1: syntax error" but now got results.
removed "-global_quality 18" ffmpeg parameter from the benchmark.sh file

**Comment by saifer92** [comment]
Hi, I encountered the same problem but I got no results by removing that argument.
