### ISSUE TITLE
Fallback to RAPL power measurement feature available in AMD and Intel CPUs newer than 2012

### ISSUE THREAD

**Issue by ypid** [cptmorgan-rh/quicksync_calc#4]
Modern CPUs can measure their own power, even what part of the CPU uses how much power. This could be very interesting to integrate into the benchmark. For example [Uncore/PP1](https://hubblo-org.github.io/scaphandre-documentation/explanations/rapl-domains.html) should be the power consumption of the iGPU excluding the CPU cores. I don’t have time to test this right now but I thought I ping @ironicbadger here as well. Maybe someone interested wants to look into this, especially as new benchmark reports are posted frequently still on https://gist.github.com/ironicbadger/5da9b321acbe6b6b53070437023b844d

* https://hubblo-org.github.io/scaphandre-documentation/explanations/rapl-domains.html
* https://hubblo-org.github.io/scaphandre-documentation/references/sensor-powercap_rapl.html
* https://hubblo-org.github.io/scaphandre-documentation/tutorials/getting_started.html

Edit: After reading the script and the [intel_gpu_top man page](https://manpages.debian.org/testing/intel-gpu-tools/intel_gpu_top.1.en.html) more closely, I guess the intel_gpu_top already collects the power info from RAPL. Still, Scaphandre could be very interesting for further deep dive into power usage during the benchmark.

**Comment by cptmorgan-rh** [comment]
Thanks we will take it into consideration.
